### ISSUE TITLE
SSR how to set defaultBreakpoint value in Nuxt Module from serverMiddleware function?

### ISSUE THREAD

**Issue by Manieck** [vanhoofmaarten/nuxt-mq#23]
Hi All

I can't find a solution for this for a long time.

I have serverMiddleware function:

device-detect.js
```
import parser from 'ua-parser-js';

export default (req, res, next) => {
  const ua = parser(req.headers['user-agent']);
  console.log(ua.device.type);  // returns: console, mobile, tablet, smarttv, wearable, embedded
  req.device = ua.device.type;  // I tried by req
  next();
}
```
nuxt.config.js
```
serverMiddleware: [
    '~/server_middlewares/device-detect.js'
  ]
```

And now I would like to set the defaultBreakpoint value in accordance with what this function decodes here

```
{
  modules: [
    ['nuxt-mq']
  ],

 'mq': {
    defaultBreakpoint: < how to get device from function device-detect.js ?>,
    breakpoints: {
      sm: 450,
      md: 1250,
      lg: Infinity,
    }
  }
}

```

Do you have any idea for this?

Regards

**Comment by vanhoofmaarten** [comment]
Hi @Manieck, thank you for your interesting question.

I tried a few things out.

First I tried to alter the default `$mq` value from a [(router) middleware](https://nuxtjs.org/guide/routing#middleware). An example is available [here](https://codesandbox.io/s/github/vanhoofmaarten/nuxt-mq-issue-23/tree/scenario/middleware). Without success as you can see.

Thinking a bit longer about your use case, I would suggest you to define a custom [Nuxt plugin](https://nuxtjs.org/guide/plugins/) which you can then inject in to the server and client context. I provided an example for you [here](https://codesandbox.io/s/github/vanhoofmaarten/nuxt-mq-issue-23/tree/scenario/plugin). You can then do logic operations with both `$mq` and `$ua` in a computed value in a component or mixin.

I hope my answer helped you with your problem.

**Comment by Manieck** [comment]
Hi, Thx for answer.

I traced vue-mq
$mq is computed field and can't be changed.
```
computed: {
        $mq: function $mq() {
          return reactorComponent.currentBreakpoint;
        }
      },
```
I solved the problem differently.
In vue-mq in function install I changed created:

before
```
created () {
      if (this.$isServer) reactorComponent.currentBreakpoint = defaultBreakpoint
    },
```
after
```
created() {
        if (this.$isServer) {
          if (Vue.prototype.$mqDefaultBreakpoint) {
            reactorComponent.currentBreakpoint = Vue.prototype.$mqDefaultBreakpoint;
          } else {
            reactorComponent.currentBreakpoint = defaultBreakpoint;
          }
        }
      },
```
I used vue-mq instead nuxt-mq
In my plugin media-query.js before Vue.use I set $mqDefaultBreakpoint
```
import Vue from 'vue';
import VueMq from 'vue-mq';
import { mqoptions } from './mq-options';

export default ({ req }) => {
  const op = mqoptions(req); // set object with mq options and device from serverMiddleware

  Vue.prototype.$mqDefaultBreakpoint = op.defaultBreakpoint;
  Vue.use(VueMq, op);
}
```
Now all is working fine.

Regards
