### ISSUE TITLE
Not work with nuxt static generated pages

### ISSUE THREAD

**Issue by davision** [vanhoofmaarten/nuxt-mq#6]
Looks like this module does not work with static generated pages. Or am I missing something?

**Comment by vanhoofmaarten** [comment]
Thank you raising this issue. You aren't missing something. This module is currently not compatible with static generated pages. I will try to provide a solution. Suggestions are welcome.

**Comment by vanhoofmaarten** [comment]
I published a fix in v1.1.3. 

`npm i nuxt-mq@latest`
