### ISSUE TITLE
Question about mq, SSR and computed class bindings

### ISSUE THREAD

**Issue by anthonygore** [vanhoofmaarten/nuxt-mq#7]
I've got a tricky problem using this plugin. Let me explain with an example...

Say you have two breakpoints, mobile, and desktop. You set the default to desktop.

You have a class binding based on the breakpoint i.e.

```
<template>
  <div :class="classes></div>
</template>
<script>
export default {
  computed: {
    classes() { return { 'is-desktop': this.$mq === 'desktop' } }
  }
}
</script>
```

The `is-desktop` class will be in the server rendered page since `desktop` is default.

Now imagine the app loads in the client and it's a mobile device. `$mq` is now set to `mobile`.

Vue will not re-render the component in the page in the hydration process and so the `is-desktop` class will stay in the DOM until $mq is updated during the app's lifecycle.

You need to manually use `Vue.$forceUpdate` in the `mounted` hook to force Vue to re-render the component and acknowledge the new value of `$mq`.

Is my understanding right or is there something I'm missing?

**Comment by vanhoofmaarten** [comment]
Thank you for raising this issue. I see you already found a solution in the main dependency of this module. https://github.com/AlexandreBonaventure/vue-mq/pull/25

I will try to update this package as soon vue-mq has upgraded.

**Comment by Manieck** [comment]
I have the same problem but after restart nuxt server is OK.
