### ISSUE TITLE
Test in computed property

### ISSUE THREAD

**Issue by yossansr** [vanhoofmaarten/nuxt-mq#84]
Can anyone give example of testing computed property with $mq value. 
My problem is I don't know what the proper way to access the value of $mq in test file.

**Comment by yossansr** [comment]
Yes I am using Jest with vue-test-utils. I want to test when $mq has condition of each breakpoint. But, I don't know how to access value of $mq in .test.js file

**Comment by vanhoofmaarten** [comment]
Hi @yossansr,

I believe you'll have to use the mock feature of vue-test-utils, to mock the value of $mq in your test. See: https://vue-test-utils.vuejs.org/guides/#common-tips

Does this help you along?

**Comment by yossansr** [comment]
Ohh yeah it works. I am new with Vue, thanks a lot for the help @vanhoofmaarten

**Comment by vanhoofmaarten** [comment]
@yossansr My pleasure! Thanks for closing the issue and good luck on your new adVuenture 😄
