### ISSUE TITLE
Potential Memory Leak in plugin.js

### ISSUE THREAD

**Issue by Cobertos** [vanhoofmaarten/nuxt-mq#95]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[x] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**

If I'm reading it right, the [documentation on plugin function syntax](https://nuxtjs.org/docs/2.x/directory-structure/plugins#inject-in-root--context) has a warning at the very bottom of the section.

> Don't use Vue.use(), Vue.component(), and globally, don't plug anything in Vue inside this function, dedicated to Nuxt injection. It will cause memory leak on server-side.

It seems like [`Vue.use()` is being used inside the plugin function](https://github.com/vanhoofmaarten/nuxt-mq/blob/develop/lib/templates/plugin.js#L6). Does that sound right? It would need to be refactored if so.

**Comment by vanhoofmaarten** [comment]
Hi Corbertus,

I believe you are correct.

The code should be refactored that it [does not export a function](https://nuxtjs.org/docs/2.x/directory-structure/plugins#vue-plugins).
